services:
  - type: web
    name: rpv-industrial-supply
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SITE_URL
        value: https://rpv-industrial-supply.onrender.com
